### ISSUE TITLE
How to make formations rotate/face toward to something?

### ISSUE THREAD

**Issue by 94Git** [Matthew-J-Spencer/Formations#1]
Good job! But I still have some questions:
How to make formations rotate/face toward to something? Like formations in _Total War_

**Comment by Matthew-J-Spencer** [comment]
Without using complex vector maths, instead of just storing vectors you could store transforms. Now when you rotate your parent, the transforms also rotate. Now just lerp your units to the transforms instead of just the local vector positions. 

Downside is that you now have a bunch of additional GameObjects in the scene.
